dbt_glaredb_quickstart:
  outputs:
    dev:
      dbname: o_vAIOmhx/empty_rain
      host: proxy.glaredb.com
      pass: "{{ env_var('GLAREDB_PASSWORD')}}"
      port: 6543
      schema: public
      threads: 1
      type: postgres
      user: 2g7nT1ShV4zA
  target: dev